name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
        run: mkdir -p path/to/artifact

      - name: Run a one-line script
        run: echo "Hello, world!" > path/to/artifact/artifact.txt
        
      - name: test
        run: npm test
        
      - name: upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/artifact.txt
      
