name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
        
      - name: Simulate an error
        run: echo "About to fail" ; exit 1

      - name: Another greeting
        run: echo "Hello, world!"
        
      - name: test
        run: npm test
        
      - name: upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
          if-no-files-found: error
